NAME="cvae-su"
z_dim=64
config={
    "privater":{
        "type":"cvae-su",
        "z_dim":z_dim,
        "rec_x_weight":10
    },
    "dataset":{
        "type":"ferg"
    },
    "trainer":{
        "type":"keras",
        "epochs":100
    },
    "evaluaters":[
        {"type":"utility",
         "z_dim":z_dim
        },
        {"type":"private",
         "z_dim":z_dim
        },
        {"type":"reconstruction",
         "base_dir": NAME
        }
    ]
}
