NAME="vae-test"
z_dim=64
config={
    "privater":{
        "type":"gpf",
        "z_dim":z_dim,
        "p_dim":2,
        "fake_rec_z_weight":100,
        "real_rec_x_weight":1
    },
    "dataset":{
        "type":"ferg"
    },
    "trainer":{
        "type":"adv",
        "epochs":100
    },
    "evaluaters":[
        {"type":"utility",
         "z_dim":z_dim
        },
        {"type":"private",
         "z_dim":z_dim
        },
        {"type":"reconstruction",
         "base_dir": NAME
        }
    ]
}
